{"title": "CentOS python-docs BugFix Update", "type": "bugfix", "description": "CentOS python-docs BugFix Update", "release": "el7", "version": "2", "severity": "Low", "status": "final", "updated": "2020-10-20 18:48:53", "issued": "2020-10-20 18:48:53", "pkglist": [{"packages": [{"arch": "noarch", "epoch": "0", "filename": "python-docs-2.7.5-3.el7.noarch.rpm", "release": "3.el7", "name": "python-docs", "sum": "d7a07e57353f3f55a3751ebc7a1d7a6ec03fcfc10797f9598b799339e4d6b295", "sum_type": "sha256"}]}], "id": "CEBA-2019:2322", "from": "centos-announce@centos.org", "references": [{"href": "https://access.redhat.com/errata/RHBA-2019:2322", "ref_id": "CEBA-2019:2322", "title": "CentOS python-docs BugFix Update", "ref_type": "bugfix"}, {"href": "https://lists.centos.org/pipermail/centos-cr-announce/2020-October/012812.html", "ref_id": "CEBA-2019:2322", "title": "CentOS python-docs BugFix Update", "ref_type": "bugfix"}, {"href": "https://lists.centos.org/pipermail/centos-cr-announce/2019-August/006106.html", "ref_id": "CEBA-2019:2322", "title": "CentOS python-docs BugFix Update", "ref_type": "bugfix"}]}